/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CapFamily, CapLeading, CapWeight } from "./types";
import { CapRichTextLevel } from "./components/cap-rich-text/types";
import { CapTextLevel } from "./components/cap-text/types";
export { CapFamily, CapLeading, CapWeight } from "./types";
export { CapRichTextLevel } from "./components/cap-rich-text/types";
export { CapTextLevel } from "./components/cap-text/types";
export namespace Components {
    interface CapRichText {
        "bodyFamily": CapFamily;
        "bodyWeight": CapWeight;
        "headingFamily": CapFamily;
        "headingWeight": CapWeight;
        "italic": boolean;
        "leading": CapLeading;
        "level": CapRichTextLevel;
    }
    interface CapText {
        "contentAfter": string;
        "contentBefore": string;
        "ellipsis": boolean;
        "family": CapFamily;
        "italic": boolean;
        "leading": CapLeading;
        "level": CapTextLevel;
        "noWrap": boolean;
        "weight": CapWeight;
    }
}
declare global {
    interface HTMLCapRichTextElement extends Components.CapRichText, HTMLStencilElement {
    }
    var HTMLCapRichTextElement: {
        prototype: HTMLCapRichTextElement;
        new (): HTMLCapRichTextElement;
    };
    interface HTMLCapTextElement extends Components.CapText, HTMLStencilElement {
    }
    var HTMLCapTextElement: {
        prototype: HTMLCapTextElement;
        new (): HTMLCapTextElement;
    };
    interface HTMLElementTagNameMap {
        "cap-rich-text": HTMLCapRichTextElement;
        "cap-text": HTMLCapTextElement;
    }
}
declare namespace LocalJSX {
    interface CapRichText {
        "bodyFamily"?: CapFamily;
        "bodyWeight"?: CapWeight;
        "headingFamily"?: CapFamily;
        "headingWeight"?: CapWeight;
        "italic"?: boolean;
        "leading"?: CapLeading;
        "level"?: CapRichTextLevel;
    }
    interface CapText {
        "contentAfter"?: string;
        "contentBefore"?: string;
        "ellipsis"?: boolean;
        "family"?: CapFamily;
        "italic"?: boolean;
        "leading"?: CapLeading;
        "level"?: CapTextLevel;
        "noWrap"?: boolean;
        "weight"?: CapWeight;
    }
    interface IntrinsicElements {
        "cap-rich-text": CapRichText;
        "cap-text": CapText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cap-rich-text": LocalJSX.CapRichText & JSXBase.HTMLAttributes<HTMLCapRichTextElement>;
            "cap-text": LocalJSX.CapText & JSXBase.HTMLAttributes<HTMLCapTextElement>;
        }
    }
}
