export type TextLevelTypes =
  | '-8'
  | '-7'
  | '-6'
  | '-5'
  | '-4'
  | '-3'
  | '-2'
  | '-1'
  | '0'
  | '+1'
  | '+2'
  | '+3'
  | '+4'
  | '+5'
  | '+6'
  | '+7'
  | '+8'
export type TextWeightTypes = 'soft' | 'strong' | 'heavy'
export type TextHeadingTypes = 1 | 2 | 3 | 4 | 5 | 6
export type TextFamilyTypes = 'sans' | 'serif' | 'mono'
