export type CapTextLevel =
	| '-8'
	| '-7'
	| '-6'
	| '-5'
	| '-4'
	| '-3'
	| '-2'
	| '-1'
	| '0'
	| '+1'
	| '+2'
	| '+3'
	| '+4'
	| '+5'
	| '+6'
	| '+7'
	| '+8'
export type CapTextWeight = 'soft' | 'strong' | 'heavy'
export type CapTextFamily = 'sans' | 'serif' | 'mono'
export type CapTextLeading = 'tight' | 'narrow' | 'compact' | 'loose' | 'open'
